# ??? Server ???????????????????????????????????????????
server.port=8081

# ??? Database ?????????????????????????????????????????
spring.datasource.url=jdbc:postgresql://localhost:5433/alten_copilot
spring.datasource.username=postgres
spring.datasource.password=hamza

# ??? JPA / Hibernate ??????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Removes dialect warning ? Spring Boot auto-detects PostgreSQL
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Removes open-in-view warning ? we are stateless REST, no view rendering
spring.jpa.open-in-view=false

# ??? App name ?????????????????????????????????????????
spring.application.name=auth-service

# ??? JWT ??????????????????????????????????????????????
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=900000
jwt.refresh-expiration=604800000

# ??? Swagger ??????????????????????????????????????????
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.try-it-out-enabled=true