# ??? Server ???????????????????????????????????????????
server.port=8083

# ??? Database ?????????????????????????????????????????
spring.datasource.url=jdbc:postgresql://localhost:5433/alten_copilot
spring.datasource.username=postgres
spring.datasource.password=hamza

# ??? JPA / Hibernate ??????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ??? File Upload ??????????????????????????????????????
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
document.upload.path=uploads/documents

# ??? App name ?????????????????????????????????????????
spring.application.name=document-service

# ??? RAG Service URL ??????????????????????????????????
rag.service.url=http://localhost:8085

# ??? JWT ??????????????????????????????????????????????
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=900000
jwt.refresh-expiration=604800000

# ??? Swagger ??????????????????????????????????????????
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.try-it-out-enabled=true